name = "alicesaidhi/vide"
version = "0.3.1-lite.671"
description = "vide with types"
authors = ["centau"]
license = "MIT"
includes = ["src/*", "README.md", "pesde.toml"]

[target]
environment = "roblox"
build_files = ["src"]
lib = "src/init.luau"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

