[package]
name = "alicesaidhi/vide"
description = "Fork of vide, comes with Roblox Instance Types"
license = "MIT"
version = "0.3.1-lite.649"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src"]
exclude = [
    ".github",
    "docs",
	"test",
	".gitattributes",
	".gitignore",
    ".luaurc",
	"CHANGELOG.md",
	"README.md",
    "todo.md"
]
